### ISSUE TITLE
INIT ERROR - Trial expired Tuya Developer Platform

### ISSUE THREAD

**Issue by Domy81** [msillano/IoTwebUI#13]
Purtroppo oggi ho scoperto di non poter più accedere con IoTwebUI v.2.1.1 poichè il periodo di prova su Tuya Developer Platform è terminato. Soluzioni? Oppure ho attivato all'inizio qualcosa che non serviva e neanche c'è bisogno?
Comunque ora ho fatto richiesta di prolungamento, ma solo di altri 6 mesi del periodo trial, quindi è sempre una soluzione temporanea!

![chrome error 2](https://github.com/user-attachments/assets/6fca63c4-3dcb-41f0-9c31-5192a51a5505)
![Tuya development](https://github.com/user-attachments/assets/9e498cc6-4c5b-4de4-9804-3b4e564e9975)

**Comment by msillano** [comment]
E' la strategia Tuya... Sanno benissimo le motivazioni dei loro 'sviluppatori' !
E' dal 2019 che rinnovo: non preoccuparti troppo.
Ciao

**Comment by Domy81** [comment]
> E' la strategia Tuya... Sanno benissimo le motivazioni dei loro 'sviluppatori' ! Pensa a tutti gli utenti Tuya + HA ;) E' dal 2020 che rinnovo: non preoccuparti troppo. Comunque mi fa piacere che lo stai usando e che ti trovi bene (altrimenti lo avrei saputo!) Ai primi di settembre la versione 2.2 ! Ciao
> 
> P.S. C'è un solo vincolo, gli accessi mensili all'API: Usandolo ininterrottamente, usare un loop di 2 minuti o più.

Aaah, ok, bene! In effetti mi hanno rinnovato subito la richiesta di prolungamento!
Si sì, ogni tanto lo uso, anche se non ho avuto molto tempo per approfondire le nuove funzionalità e customizzarlo ulteriori!
Devo partire per qualche giorno di ferie e volevo vedere le batterie dei sensori... Tutti in colpo, sulla stessa pagina! 😉✌️
Grazie
