### ISSUE TITLE
Errore in Ubuntu [object_proxy.cc]

### ISSUE THREAD

**Issue by msillano** [msillano/IoTwebUI#15]
[Andrea Susini](https://www.facebook.com/groups/633613903939633/user/1561167614/?__cft__[0]=AZX6PO8K6vmW0OGFvGitWooOyNSoPAc3XVocH8KEZvDhmuo_cfJrOPT6M5geD1sLCz4-1K0mjGQZil-PkXrN0CDwpaFJZXnQ7C2HZG6IpaoSxBkhqGu7hgKouaetll02L8eeB-aHKOV2QmNGIbTKAY8L-ysiCxzwmculSKKYc2c94g&__tn__=R]-R)
Non riesco ad andare avanti:
ERRORE del TOKEN Tuya
Accesso a Tuya fallito. Verificare credenziaoli e CORS (Ho provato da w2k10 e ubuntu)
Le credenziali sono quelle che uso per accedere al cloud, creare nuovi progetti etc etc..... Il datacenter è quello giusto, europeo.
A console vedo l'errore:
[298300:298300:0906/184200.443667:ERROR:[object_proxy.cc](http://object_proxy.cc/?fbclid=IwZXh0bgNhZW0CMTAAAR327zPOekguTQr03rNecUzgRVhIwbhth52DPx177PArbl1pGSLo7IeBS30_aem_Ghobq53qKfhCcxRkoRUdfA)(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
... ma qui mi fermo e chiedo aiuto....
Qualche idea ? Tnx.
(post originale https://www.facebook.com/groups/tuyaitalia/posts/1431852194115796/?comment_id=1481928352441513 )

**Comment by msillano** [comment]
"ERRORE del TOKEN Tuya" indica sia un errore specifico, sia un errore generico avvenuto nella fase di avvio del programma.
Le versioni 2.1.1 e 2.2 sono state provate con Chrome in Win11, mac OS 10.11, Android, ma non su Ubuntu.
Poiché il codice è in Javascript,  IoTwebUI è eseguito nell'ambiente browser.
Alcune info: che versione di IoTwebUI ? Con che browser ha provato?
'Freedesktop' e 'ScreenSaver' non mi suggeriscono niente... La gestione schermo è affidata a librerie  affidabili: bootstrap@5.3.3 e vis-network. 

Direi che il problema è di incompatibilità/non completezza del Javascript presente sul sistema Ubuntu.

Consiglio di fare l'installazione su una pennetta e di provarla su altri PC.
Se il problema si è presentato con IoTwebUI 2.2, provare con la versione 2.1.1  
Infatti nella versione 2.2 è stata aggiunto un accesso ad un websocket (REST: il codice che lo crea, server.js, richiede nodejs, vedi documentazione https://github.com/msillano/IoTwebUI/blob/main/RESTserver/LEGGIMI-REST22.md).  Ma non è essenziale negli  ambienti provati: se manca, segnala in console solo 'websocket non trovato', senza errore. Forse in un ambiente diverso potrebbe generare un errore? La vers, 2.1.1. non accede al websocket.
Cordialente

**Comment by suso-suso** [comment]
dettagli ambiente X:
Chrome Version 128.0.6613.113 (Official Build) (64-bit). Ubuntu su Ubuntu 20.04 lts.
Ho provato anche da una vm windows 2010 con stesso errore sul browser:  ERRORE del TOKEN Tuya
    Accesso a Tuya fallito. Verificare credenziaoli e CORS (vedi console...) 
    La console mi scrive questo:
    C:\Users\suso.WIN-S6HUA21QITS\Desktop\IoTwebUI.2.2\IoTwebUI.2.2>run_me.bat

C:\Users\suso.WIN-S6HUA21QITS\Desktop\IoTwebUI.2.2\IoTwebUI.2.2>REM  ===== Start command for webAPP TuyaUIweb using CHROME

C:\Users\suso.WIN-S6HUA21QITS\Desktop\IoTwebUI.2.2\IoTwebUI.2.2>SET browser="C:\Programmi\Google\Chrome\Application\chrome.exe"

C:\Users\suso.WIN-S6HUA21QITS\Desktop\IoTwebUI.2.2\IoTwebUI.2.2>SET IoTwebUI="C:\Users\suso.WIN-S6HUA21QITS\Desktop\IoTwebUI.2.2\IoTwebUI.2.2\IoTwebUI.html"

C:\Users\suso.WIN-S6HUA21QITS\Desktop\IoTwebUI.2.2\IoTwebUI.2.2>start "" "C:\Programmi\Google\Chrome\Application\chrome.exe" --user-data-dir="C://chrome session" --disable-web-securit
y  --disable-popup-blocking --auto-accept-camera-and-microphone-capture --app="C:\Users\suso.WIN-S6HUA21QITS\Desktop\IoTwebUI.2.2\IoTwebUI.2.2\IoTwebUI.html"
C:\Users\suso.WIN-S6HUA21QITS\Desktop\IoTwebUI.2.2\IoTwebUI.2.2>

Non sembra esserci errore. Domanda, come login usi l'email ? Non vorrei che la "@" venisse interpretata male.....



Altri dettagli da devtool:
SpeechRecognition enabled.
tuyaHTTP.js:33 Array(3)0: "ERROR tuyaHTTP"1: {method: 'GET', headers: {…}, payload: null, url: 'https://openapi.tuyaeu.com/v1.0/token?grant_type=1'}2: {code: 2009, msg: 'clientId is invalid', success: false, t: 1725726461715, tid: '1acdd8b96d3611efb77736033862a1ba'}length: 3[[Prototype]]: Array(0)
tuyaui02.2.js:266 ERROR: no token. Check credentials and CORS
tuyaui02.2.js:327 Uncaught (in promise) TOKEN FATAL ERROR
restIoT.js:209 WebSocket connection to 'ws://localhost:3030/' failed: 
(anonymous) @ restIoT.js:209
restIoT.js:271 Disconnected from WebSocket server

Tnx

**Comment by msillano** [comment]
[Marco Sillano] funziona anche sotto ubuntu 20.04 lts. Mio errore da pivello.... Avevo frainteso quali fossero le credenziali. Non quelle del login al portale ma quelle del progetto dentro il portale....
Sorry....
( original post https://www.facebook.com/groups/tuyaitalia/posts/1431852194115796/?comment_id=1481928352441513&reply_comment_id=1482944919006523 )
