### ISSUE TITLE
Errore di inizializzazione

### ISSUE THREAD

**Issue by sn4k326** [msillano/IoTwebUI#19]
Sto provando il primo avvio, ho impostato tutto come da guida, ma mi da questo errore

![image](https://github.com/user-attachments/assets/a2a800c8-9601-4c93-bcb9-4ae8c47e7192)

**Comment by sn4k326** [comment]
ok, ho risolto quel problema, effettivamente era dovuto alla subscription, però ora mi escono questi alert, da quale file li dovrei modificare?


![image](https://github.com/user-attachments/assets/234ffd0b-f0b0-43d6-b2e3-1cd84ca07432)

**Comment by msillano** [comment]
````Scusami, colpa mia! Nel fare il file ZIP non ho pulito alcune prove: non trovando le stesse device dà ovviamente errore!
Già corretto, se scarichi IoTwebUI.2.2.1.zip è OK.

Alternativa:  apri il file "\usrrules02.2.js" e cancella le righe indicate:
```
var usrRules = `
// here your RULEs
// for test: you can delete this
   if (TRIGBYNAME('spegni luce')) VOICE ("Fatto: 'spegni la luce'");
   if (TRIGBYNAME("Pippo")) VOICE ("Trovato Pippo");
   if (TRIGBYNAME("chiamata Pippo")) TRIGRULE("pippo"), VOICE("chiamo Pippo");
===================================== CANCELLA DA QUI ALLA FINE!
   BATTERY01();                //  MACRO call
   if (TRIGBYNAME("Batterie CIRCEO")) SETXDEVICESTATUS("Battery test", 'home', 'CIRCEO'),REFRESH(),VOICE("Batterie del Circeo"), REFRESH('cloud');
   if (TRIGBYNAME("Batterie ROMA")) SETXDEVICESTATUS("Battery test", 'home', 'ROMA'),REFRESH(),VOICE("Batterie di Roma"),REFRESH('cloud');

  // data-processing x-device (temperaturedata) for clima01 HTML
  if (!GETATTRIBUTE("temperaturedata", "name", false)) ADDXDEVICE('ADMIN', "System", "temperaturedata"), SETXDEVICEONLINE("temperaturedata", true);
  SETXDEVICESTATUS("temperaturedata",  "soggiorno", ROUND(GET("bf3d00a6c2xxxxxx", "va_temperature")/10, 1)+" °C");
  SETXDEVICESTATUS("temperaturedata",  "letto",     ROUND(GET("bfc5451737cbfexxxxxx, "va_temperature")/10, 1)+" °C");
  SETXDEVICESTATUS("temperaturedata",  "ospiti",    ROUND(GET("bf931b4999e23xxxxxx", "va_temperature")/10, 1)+" °C");
  SETXDEVICESTATUS("temperaturedata",  "esterno",   ROUND(GET("bf37d9e44c947xxxxxx", "va_temperature")/10, 1)+" °C");

  SETXDEVICESTATUS("XMain AC", "PVpower",   ROUND(GET("bf5c74764a3cxxxxxx", "power_total")/10, 1));
  SETXDEVICESTATUS("XMain AC", "FRpower",   ROUND(GET("06100018c45bxxxxxx",   "cur_power")/10, 1));

  CLONER01("bf040b2553d9xxxxxx", "X-TY-08Z") ;
================================== FINE CANCELLAZIONE !!!!
`;

```
Le 'REGOLE' 
```
   if (TRIGBYNAME('spegni luce')) VOICE ("Fatto: 'spegni la luce'");
   if (TRIGBYNAME("Pippo")) VOICE ("Trovato Pippo");
   if (TRIGBYNAME("chiamata Pippo")) TRIGRULE("pippo"), VOICE("chiamo Pippo");
```
   Puoi tenerle: non usano device (non danno errori) e sono utili per fare prove. Tieni il volume a metà, parlano !
   Le puoi sempre cancellare in un secondo tempo!
   
Mi scuso per il problema.

**Comment by sn4k326** [comment]
> Scusami, colpa mia! Nel fare il file ZIP non ho pulito alcune prove: non trovando le stesse device dà ovviamente errore! Già corretto, se scarichi IoTwebUI.2.2.1.zip è OK.
> 
> Alternativa: apri il file "\usrrules02.2.js" e cancella le righe indicate:
> 
> ```
> var usrRules = `
> // here your RULEs
> // for test: you can delete this
>    if (TRIGBYNAME('spegni luce')) VOICE ("Fatto: 'spegni la luce'");
>    if (TRIGBYNAME("Pippo")) VOICE ("Trovato Pippo");
>    if (TRIGBYNAME("chiamata Pippo")) TRIGRULE("pippo"), VOICE("chiamo Pippo");
> ===================================== CANCELLA DA QUI ALLA FINE!
>    BATTERY01();                //  MACRO call  per avere la x-device battery0i - vedi in ADDON
>    if (TRIGBYNAME("Batterie CIRCEO")) SETXDEVICESTATUS("Battery test", 'home', 'CIRCEO'),REFRESH(),VOICE("Batterie del Circeo"), REFRESH('cloud');
>    if (TRIGBYNAME("Batterie ROMA")) SETXDEVICESTATUS("Battery test", 'home', 'ROMA'),REFRESH(),VOICE("Batterie di Roma"),REFRESH('cloud');
> 
>   // data-processing x-device (temperaturedata)  middleware per la pagina clima01 HTML  vedi html-Clima01
>   if (!GETATTRIBUTE("temperaturedata", "name", false)) ADDXDEVICE('ADMIN', "System", "temperaturedata"), SETXDEVICEONLINE("temperaturedata", true);
>   SETXDEVICESTATUS("temperaturedata",  "soggiorno", ROUND(GET("bf3d00a6c2xxxxxx", "va_temperature")/10, 1)+" °C");
>   SETXDEVICESTATUS("temperaturedata",  "letto",     ROUND(GET("bfc5451737cbfexxxxxx, "va_temperature")/10, 1)+" °C");
>   SETXDEVICESTATUS("temperaturedata",  "ospiti",    ROUND(GET("bf931b4999e23xxxxxx", "va_temperature")/10, 1)+" °C");
>   SETXDEVICESTATUS("temperaturedata",  "esterno",   ROUND(GET("bf37d9e44c947xxxxxx", "va_temperature")/10, 1)+" °C");
> 
> // altre prove: unisce le misure di due meter in un singolo  x-device: middleware per un grafico (HTML - test01)
>   SETXDEVICESTATUS("XMain AC", "PVpower",   ROUND(GET("bf5c74764a3cxxxxxx", "power_total")/10, 1));
>   SETXDEVICESTATUS("XMain AC", "FRpower",   ROUND(GET("06100018c45bxxxxxx",   "cur_power")/10, 1));
> 
> ================================== FINE CANCELLAZIONE !!!!
> `;
> ```
> 
> Le 'REGOLE'
> 
> ```
>    if (TRIGBYNAME('spegni luce')) VOICE ("Fatto: 'spegni la luce'");
>    if (TRIGBYNAME("Pippo")) VOICE ("Trovato Pippo");
>    if (TRIGBYNAME("chiamata Pippo")) TRIGRULE("pippo"), VOICE("chiamo Pippo");
> ```
> 
> Puoi tenerle: non usano device (non danno errori) e sono utili per fare prove. Tieni il volume a metà, parlano ! Le puoi sempre cancellare in un secondo tempo!
> 
> Mi scuso per il problema.
> 
> P.S. Vedo sullo sfondo che comunque funziona, bene! Inoltre Questo problema NON è bloccante: se cancelli i pop-up puoi continuare normalmente!
> 
> Ciao, buon divertimento!

In realtà sto già utilizzando la 2.2.1, comunque ora provo a fare queste modifiche manualmente, grazie

**Comment by sn4k326** [comment]
perfetto, ora funziona tutto
